### ISSUE TITLE
Prompt error

### ISSUE THREAD

**Issue by JoschaP** [mateodelnorte/meta#114]
~ meta -V
1.2.16

~ meta git status
warn: The current directory is not a meta repo:
  /Volumes/Code/Project/interface/app

The closest meta repo is:
  /Volumes/Code/Project/interface/.meta

Would you like to:
  - continue in the closest meta repo? [y/enter]
  - continue in the current directory? [c]
  - cancel and exit? [x]
/usr/local/lib/node_modules/meta/node_modules/get-meta-file/index.js:53
    const answer = prompt(message).toLowerCase() || 'y';
                          ^

ReferenceError: message is not defined
    at module.exports (/usr/local/lib/node_modules/meta/node_modules/get-meta-file/index.js:53:27)
    at module.exports (/usr/local/lib/node_modules/meta/node_modules/meta-loop/index.js:12:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/meta/node_modules/meta-git/bin/meta-git-status:20:1)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)

**Comment by patrickleet** [comment]
@aleclarson 
https://github.com/mateodelnorte/get-meta-file/commit/04aea40f1c7a8119a15e4a50d4e8ee7bf68369f9#diff-168726dbe96b3ce427e7fedce31bb0bcL29

**Comment by aleclarson** [comment]
Whoops. Forgot to test that code path. 😅

**Comment by patrickleet** [comment]
let's reopen til PR with update to get-meta-file is merged - assuming renovatebot will make that soon..

**Comment by aleclarson** [comment]
@patrickleet The `meta` package does not depend on `get-meta-file` directly.

**Comment by patrickleet** [comment]
well then

**Comment by patrickleet** [comment]
lol

**Comment by mateodelnorte** [comment]
yea, there's a fun cascade in this one. we should double down on tests so this type of a cascade is very rare.
