### ISSUE TITLE
windows has trouble chaining git style subcommands

### ISSUE THREAD

**Issue by mateodelnorte** [mateodelnorte/meta#2]
This is likely happening because npm is wrapping bin files in .cmd files. 
```
C:\Program Files (x86)\Nodist\v-x64\6.9.1\node_modules\meta\node_modules\.bin\meta-git:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by mateodelnorte** [comment]
fixed in most recent push to mateodelnorte/commander.js and included in meat.
