### ISSUE TITLE
projects property unreadable from .meta file

### ISSUE THREAD

**Issue by jawaaad** [mateodelnorte/meta#44]
Hi, I ran a command meta git pull, it pulled the newly created child repo, fixed conflicts and staged changes, but when i run command meta git status, the following error is thrown 
`TypeError: Cannot read property 'projects' of null
    at module.exports (/Users/embrace/.nvm/versions/node/v8.11.3/lib/node_modules/meta/node_modules/meta-git/node_modules/meta-loop/index.js:13:25)
    at Object.<anonymous> (/Users/embrace/.nvm/versions/node/v8.11.3/lib/node_modules/meta/node_modules/meta-git/bin/meta-git-branch:25:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
here is my meta file defintion
{
  "projects": {
    "auth": "path to repo",
    "chat": "path to repo",
    "groupchat": "path to repo"
     }
}

what's going on here?

**Comment by metronlabsllc** [comment]
I am having the same exact issue right now.

`TypeError: Cannot read property 'projects' of null
    at module.exports (/usr/local/lib/node_modules/meta/node_modules/meta-git/node_modules/meta-loop/index.js:13:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/meta/node_modules/meta-git/bin/meta-git-branch:25:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3`

**Comment by mateodelnorte** [comment]
You probably have a mal-formed .meta file. Extra commas or missing commas?
