### ISSUE TITLE
meta fails on first run 

### ISSUE THREAD

**Issue by mateodelnorte** [mateodelnorte/meta#67]
getting the following on first run, after a new install
```
meta
TypeError: Cannot read property 'split' of undefined
    at module.exports (/Users/matt/n/lib/node_modules/meta/lib/findPlugins.js:33:25)
    at Object.exports.run (/Users/matt/n/lib/node_modules/meta/index.js:24:23)
    at Object.<anonymous> (/Users/matt/n/lib/node_modules/meta/bin/meta:8:15)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

**Comment by mateodelnorte** [comment]
Looks like the offending code is https://github.com/mateodelnorte/meta/blob/master/lib/findPlugins.js#L33. @aleclarson does NODE_PATH work with pre v11 node?
